namespace MochaTool.InteropGen;

internal class BaseCodeGenerator
{
	protected IEnumerable<IUnit> Units { get; }

	public BaseCodeGenerator( IEnumerable<IUnit> units )
	{
		Units = units;
	}

	protected string GetHeader()
	{
		return $"""
		//------------------------------------------------------------------------------ 
		// <auto-generated> 
		// This code was generated by a tool. 
		// InteropGen generated on {DateTime.Now}
		// 
		// Changes to this file may cause incorrect behavior and will be lost if 
		// the code is regenerated. 
		// </auto-generated> 
		//------------------------------------------------------------------------------
		""";
	}
}
