internal class BaseCodeGenerator
{
	protected List<IUnit> Units { get; } = new();

	public BaseCodeGenerator( List<IUnit> units )
	{
		Units = units;
	}

	protected string GetHeader()
	{
		return $"""
		//------------------------------------------------------------------------------ 
		// <auto-generated> 
		// This code was generated by a tool. 
		// InteropGen generated on {DateTime.Now}
		// 
		// Changes to this file may cause incorrect behavior and will be lost if 
		// the code is regenerated. 
		// </auto-generated> 
		//------------------------------------------------------------------------------
		""";
	}
}
